---
title: "Hood Replication Project"
author: "Jacob Hood"
date: "4/1/2021"
output: pdf_document
---

## Setting up environment 
```{r setup, include=FALSE, results = "asis"}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
p_load(tidyverse, ipumsr, kableExtra, data.table, seg, stargazer, tables, xtable, gmodels)
```

## Loading data into environment
```{r loading data}
ddi <- read_ipums_ddi("usa_00004.xml")
data <- read_ipums_micro(ddi)
crosswalk_data <- read.csv("occ_crosswalk.csv")
```

## Cleaning data
```{r selecting variables}
# Selecting variables to keep 
data_clean <- data %>%
  select(YEAR, SAMPLE, SERIAL, PERNUM, PERWT, REGION,	METRO,	NCHILD,	NCHLT5,	SEX, AGE,	MARST, RACE, HISPAN, BPL, EDUC, EDUCD, LABFORCE,	CLASSWKR, CLASSWKRD, OCC1990,	WKSWORK1, WKSWORK2,	UHRSWORK, INCWAGE)
```

```{r remove percentiles}
# Removing the top (99%) and bottom (1%) income percentiles 
data_clean <- data_clean %>% group_by(YEAR) %>% filter(INCWAGE != 0) %>% filter(INCWAGE < quantile(data_clean$INCWAGE, 0.99) & INCWAGE > quantile(data_clean$INCWAGE, 0.01))
```

```{r select correct obvs}
# Filtering out people active in labor force, black or white, ages 25-59, and not Hispanic
data_clean <- data_clean %>% 
  filter(LABFORCE == 2 & AGE <= 59 & AGE >= 25 & HISPAN == 0 & RACE < 3) %>%
  filter(EDUC != 0 & INCWAGE < 999998 & UHRSWORK != 00) %>%
  filter(WKSWORK1 !=0 | WKSWORK2 != 0)  # Removing missing values for education and income
```

```{r}
# For grouped school years, setting years of schooling to the mean
data_clean <- data_clean %>% mutate(EDUY = ifelse(EDUC == 01, 4, ifelse(EDUC == 02, 9, ifelse(EDUC == 03, 11, ifelse(EDUC == 04, 12, ifelse(EDUC == 05, 13, ifelse(EDUC == 06, 14, ifelse(EDUC == 07, 15, ifelse (EDUC == 08, 16, ifelse (EDUC == 08, 17, ifelse(EDUC == 09, 17, ifelse(EDUC == 10, 18, 21))))))))))))
```

```{r}
# Joining with crosswalk data
# I have to convert the data and merge it otherwise my computer's memory gets exhausted
# So apologies for the ugly code!

names(crosswalk_data)[names(crosswalk_data) == "occ1990"] <- "OCC1990"
# Extract the data in a data.table format 
    # can be replaced by reading from a file using fread or any other command to have both data sets as data tables.
dt1 <- as.data.table(data_clean) 
dt2 <- as.data.table(crosswalk_data)

# set the merging key in each data table
setkey(dt1, "OCC1990")
setkey(dt2, "OCC1990")
# merge data tables
dt.result <- merge(dt1, dt2, by = "OCC1990")

data_clean <- as.data.frame(dt.result)
```

```{r new variables}
# Finally, create new variables for log weekly hours worked, weekly wage, log weekly wage (all adjusted for inflation), potential work experience,
# and potential work experience squared 

# recoding WKSWORK2 to values centered on the mean for Year 2010
data_clean <- data_clean %>% mutate(ADJWKSWORK2 = ifelse(WKSWORK2 == 1, 7, ifelse(WKSWORK2 == 2, 20, ifelse (WKSWORK2 == 3, 33, ifelse(WKSWORK2 == 4, 43.5, ifelse(WKSWORK2 == 5, 48.5, 51))))))

 # adjusting for inflation (1999 dollars)
data_clean <- data_clean %>% mutate(ADJINCWAGE = ifelse(YEAR == 1980, INCWAGE*2.295, ifelse(YEAR == 1990, INCWAGE*1.334, ifelse(YEAR == 2000, INCWAGE, INCWAGE*0.764)))) %>% 
  mutate("LOGWKSWRK" = ifelse(YEAR == 2010, log(ADJWKSWORK2), log(WKSWORK1)), "WKWAGE" = ifelse(YEAR == 2010, ADJINCWAGE/ADJWKSWORK2, ADJINCWAGE/WKSWORK1), "LOGWKWAGE" = ifelse(YEAR == 2010, log(ADJINCWAGE/ADJWKSWORK2), log(ADJINCWAGE/WKSWORK1)), "PWRKEXP" = (AGE - EDUY - 6), "SQ_PWRKEXP" = PWRKEXP^2, "LOGUHRS" = log(UHRSWORK))
```

```{r new variables}
# Renaming the dummy sex and race variables to character strings, and creating a new variable for both race and gender
data_clean <- data_clean %>% mutate(GENDER = ifelse(SEX == 1, "male", "female")) %>% mutate(RACE = ifelse(RACE == 1, "white", "black" )) %>% mutate(RACEGENDER = ifelse(GENDER == "male" & RACE == "white", "white male", ifelse(GENDER == "female" & RACE== "white", "white female", ifelse(GENDER == "male" & RACE == "black", "black male", "black female"))))
```

```{r}
# Creating variable for Foreign Born (=1)
data_clean <- data_clean %>% mutate(ForeignBorn = ifelse(BPL >= 150, 1, 0)) %>%
# Creating variable for Public Sector (=1)
mutate(PublicSector = ifelse(CLASSWKRD >= 24 & CLASSWKRD < 29, 1, 0))
```

```{r}
# Creating variable for College (=1)
data_clean <- data_clean %>% mutate(College = ifelse(EDUC >= 10 , 1, 0 )) %>%

# Creating variable for Some College (=1)
mutate(SomeCol = ifelse(EDUC > 06 & EDUC < 10, 1, 0)) %>%

# Creating variable for High School (=1)
mutate(HSGrad = ifelse(EDUC ==06, 1, 0)) %>%

  # Creating variable for Less than high school (=1)
mutate(LessHS = ifelse(EDUC < 06, 1, 0))
```

```{r}
# Creating variable for Married (=1)
data_clean <- data_clean %>% mutate(Married = ifelse(MARST == 1 | MARST ==2, 1, 0)) %>%

# Creating variable for Presence of Child Under 5 (=1)
mutate(Child5 = ifelse(NCHLT5 == 0, 0, 1))
```

```{r}
# Creating variable for Northeast Region (=1)
data_clean <- data_clean %>% mutate(Northeast = ifelse(REGION == 11 | REGION == 12, 1, 0)) %>%

# Creating variable for Midwest Region (=1)
mutate(Midwest = ifelse(REGION == 21 | REGION == 22, 1, 0)) %>%

# Creating variable for South Region (=1)
mutate(South = ifelse(REGION == 31 | REGION == 32 | REGION == 33, 1, 0)) %>%
  
# Creating variable for West Region (=1)
mutate(West = ifelse(REGION == 42 | REGION == 43, 1, 0)) %>%

# Creating variable for Metro (=1)
 mutate(Metro = ifelse(METRO >= 2, 1, 0))

```

## Descriptive Statistics 
```{r TableA1a}
# Creating TableA1a
TableA1A <- data_clean %>% filter(GENDER == "male") %>% group_by(YEAR, RACE) %>%
  summarise("Weekly wage" = mean(WKWAGE),
            "Weekly wage (logged)" = mean(LOGWKWAGE),
            "Weekly working hours" = mean(UHRSWORK),
            "Weekly working hours (logged)" = mean(LOGUHRS),
            "Public sector (=1)" = mean(PublicSector),
            "College (=1)" = mean(College),
            "Some college (=1)" =  mean(SomeCol),
            "High school graduate (=1)" =  mean(HSGrad),
            "Less than high school (=1)" =  mean(LessHS),
            "Potential work experience" =  mean(PWRKEXP),
            "Potential wok experience sq." =  mean(SQ_PWRKEXP),
            "Married (=1)" =  mean(Married),
            "Number of children" =  mean(NCHILD),
            "Child under 5 (=1)" =  mean(Child5),
            "Foreign born (=1)" =  mean(ForeignBorn),
            "Northeast region (=1)" =  mean(Northeast),
            "Midwest region (=1)" =  mean(Midwest),
            "South region (=1)" =  mean(South),
            "West region (=1)" =  mean(West),
            "Lives in metropolitan area (=1)" = mean(Metro))
TableA1A
```

```{r TableA1b}
# Creating TableA1b
TableA1B <- data_clean %>% filter(GENDER == "female") %>% group_by(YEAR, RACE) %>%
  summarise("Weekly wage" = mean(WKWAGE),
            "Weekly wage (logged)" = mean(LOGWKWAGE),
            "Weekly working hours" = mean(UHRSWORK),
            "Weekly working hours (logged)" = mean(LOGUHRS),
            "Public sector (=1)" = mean(PublicSector),
            "College (=1)" = mean(College),
            "Some college (=1)" =  mean(SomeCol),
            "High school graduate (=1)" =  mean(HSGrad),
            "Less than high school (=1)" =  mean(LessHS),
            "Potential work experience" =  mean(PWRKEXP),
            "Potential wok experience sq." =  mean(SQ_PWRKEXP),
            "Married (=1)" =  mean(Married),
            "Number of children" =  mean(NCHILD),
            "Child under 5 (=1)" =  mean(Child5),
            "Foreign born (=1)" =  mean(ForeignBorn),
            "Northeast region (=1)" =  mean(Northeast),
            "Midwest region (=1)" =  mean(Midwest),
            "South region (=1)" =  mean(South),
            "West region (=1)" =  mean(West),
            "Lives in metropolitan area (=1)" = mean(Metro))
            
TableA1B
```

```{r}
# Transposing table and exporting to latex
TableA1A <- t(TableA1A)
xtable(TableA1A)
```

```{r}
# Transposing table and exporting to latex
TableA1B <- t(TableA1B)
xtable(TableA1B)
```

```{r}
# Calculating N  men
Nwhitemen1980 <- data_clean %>% filter(RACEGENDER == "white male") %>% filter(YEAR == "1980")
nrow(Nwhitemen1980)
Nblackmen1980 <- data_clean %>% filter(RACEGENDER == "black male") %>% filter(YEAR == "1980")
nrow(Nblackmen1980)
Nwhitemen1990 <- data_clean %>% filter(RACEGENDER == "white male") %>% filter(YEAR == "1990")
nrow(Nwhitemen1990)
Nblackmen1990 <- data_clean %>% filter(RACEGENDER == "black male") %>% filter(YEAR == "1990")
nrow(Nblackmen1990)
Nwhitemen2000 <- data_clean %>% filter(RACEGENDER == "white male") %>% filter(YEAR == "2000")
nrow(Nwhitemen2000)
Nblackmen2000 <- data_clean %>% filter(RACEGENDER == "black male") %>% filter(YEAR == "2000")
nrow(Nblackmen2000)
Nwhitemen2010 <- data_clean %>% filter(RACEGENDER == "white male") %>% filter(YEAR == "2010")
nrow(Nwhitemen2010)
Nblackmen2010 <- data_clean %>% filter(RACEGENDER == "black male") %>% filter(YEAR == "2010")
nrow(Nblackmen2010)
```

```{r}
# Calculating N  women
Nwhitewomen1980 <- data_clean %>% filter(RACEGENDER == "white female") %>% filter(YEAR == "1980")
nrow(Nwhitewomen1980)
Nblackwomen1980 <- data_clean %>% filter(RACEGENDER == "black female") %>% filter(YEAR == "1980")
nrow(Nblackwomen1980)
Nwhitewomen1990 <- data_clean %>% filter(RACEGENDER == "white female") %>% filter(YEAR == "1990")
nrow(Nwhitewomen1990)
Nblackwomen1990 <- data_clean %>% filter(RACEGENDER == "black female") %>% filter(YEAR == "1990")
nrow(Nblackwomen1990)
Nwhitewomen2000 <- data_clean %>% filter(RACEGENDER == "white female") %>% filter(YEAR == "2000")
nrow(Nwhitewomen2000)
Nblackwomen2000 <- data_clean %>% filter(RACEGENDER == "black female") %>% filter(YEAR == "2000")
nrow(Nblackwomen2000)
Nwhitewomen2010 <- data_clean %>% filter(RACEGENDER == "white female") %>% filter(YEAR == "2010")
nrow(Nwhitewomen2010)
Nblackwomen2010 <- data_clean %>% filter(RACEGENDER == "black female") %>% filter(YEAR == "2010")
nrow(Nblackwomen2010)
```

```{r}
# Plotting Figure 1

data_clean$RACEGENDER <- factor(data_clean$RACEGENDER, levels=c("white male", "white female", "black male", "black female"))
# Reordering the levels of our group variable so it shows up in the right order
# when plotting

fig1data <- data_clean %>% group_by(YEAR, RACEGENDER) %>% summarise(AVGWKWAGE = mean(WKWAGE)) # grouping data by year/group and averaging weekly wage
```


```{r}
fig1 <- fig1data %>%
  ggplot(aes(YEAR, y = AVGWKWAGE, linetype = RACEGENDER)) +
  geom_line(size =1) + 
  geom_point(aes(shape = RACEGENDER), size = 4) +
  labs(x = "", y = "" , title = "") +
    scale_linetype_manual(values = c("solid", "solid", "dashed", "dashed"), label = c("White Male", "White Female", "Black Male","Black Female")) +
  scale_shape_manual(values = c(15, 17, 22, 24), label = c("White Male", "White Female" , "Black Male", "Black Female")) + 
  scale_y_continuous(limits=c(400, 1100), n.breaks = 8) +
  theme(legend.title = element_blank()) +
  theme(legend.position = "bottom") +
  geom_hline(yintercept=500) +
  geom_hline(yintercept=600) +
  geom_hline(yintercept=700) +
  geom_hline(yintercept=800) +
  geom_hline(yintercept=900) +
  geom_hline(yintercept=1000) +
  geom_hline(yintercept=1100) +
  theme(panel.background = element_blank()) + 
  theme(axis.line = element_line(color = "black")) +
  theme(axis.text = element_text(face = "bold", color = "black", size = 12)) +
  theme(legend.background = element_blank())+
  theme(legend.box.background = element_rect(colour = "black")) +
  theme(legend.key = element_rect(fill = NA)) +
  theme(legend.text = element_text(face = "bold", color = "black", size = 12)) +
  theme(legend.key.size = unit(1, "cm"))
  

ggsave("fig1.png")
```

## Regression Analysis
```{r}
# Running linear models for men, by race and year
m1980whitemen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + LOGUHRS + Metro + PublicSector + Midwest + South + West, data = Nwhitemen1980)
m1980blackmen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + LOGUHRS + Metro + PublicSector + Midwest + South + West, data = Nblackmen1980)
m1990whitemen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + LOGUHRS + Metro + PublicSector + Midwest + South + West, data = Nwhitemen1990)
m1990blackmen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + LOGUHRS + Metro + PublicSector + Midwest + South + West, data = Nblackmen1990)
m2000whitemen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + LOGUHRS + Metro + PublicSector + Midwest + South + West, data = Nwhitemen2000)
m2000blackmen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + LOGUHRS + Metro + PublicSector + Midwest + South + West, data = Nblackmen2000)
m2010whitemen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + LOGUHRS + Metro + PublicSector + Midwest + South + West, data = Nwhitemen2010)
m2010blackmen <-lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + LOGUHRS + Metro + PublicSector + Midwest + South + West, data = Nblackmen2010)

```

```{r}
# Model table for men
stargazer(m1980whitemen, m1980blackmen, m1990whitemen, m1990blackmen,m2000whitemen, m2000blackmen, m2010whitemen, m2010blackmen, type = "text")
```

```{r}
# Running linear models for women, by race and year
m1980whitewomen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + LOGUHRS + Metro + PublicSector + Midwest + South + West, data = Nwhitewomen1980)

m1980blackwomen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + LOGUHRS + Metro + PublicSector + Midwest + South + West, data = Nblackwomen1980)

m1990whitewomen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + LOGUHRS + Metro + PublicSector + Midwest + South + West, data = Nwhitewomen1990)

m1990blackwomen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + LOGUHRS + Metro + PublicSector + Midwest + South + West, data = Nblackwomen1990)
```


```{r}
m2000whitewomen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + LOGUHRS + Metro + PublicSector + Midwest + South + West, data = Nwhitewomen2000)
```


```{r}
m2000blackwomen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + LOGUHRS + Metro + PublicSector + Midwest + South + West, data = Nblackwomen2000)
```


```{r}
m2010whitewomen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + LOGUHRS + Metro + PublicSector + Midwest + South + West, data = Nwhitewomen2010)
```


```{r}
m2010blackwomen <-lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + LOGUHRS + Metro + PublicSector + Midwest + South + West, data = Nblackwomen2010)
```

```{r}
stargazer(m1980whitewomen, m1980blackwomen, m1990whitewomen, m1990blackwomen, m2000whitewomen, m2000blackwomen, m2010whitewomen, m2010blackwomen, type = "text", omit = "ser", "f")
```


```{r}
# Setting up data to calculate index of dissimilarity, men 1980

dissim1 <- table(Nwhitemen1980$occ_2digit)
dissim1 <- as.data.frame(dissim1)
dissim1 <- dissim1 %>% 
  rename(
    occ_2digit = Var1,
    white = Freq
)
dissim2 <- table(Nblackmen1980$occ_2digit)
dissim2 <- as.data.frame(dissim2)
dissim2 <- dissim2 %>% 
  rename(
    occ_2digit = Var1,
    black = Freq
    )

men1980dissim <- full_join(dissim1, dissim2, by = "occ_2digit")
men1980dissim$occ_2digit <- NULL
```


```{r}
# Setting up data to calculate index of dissimilarity, men 1990
dissim3 <- table(Nwhitemen1990$occ_2digit)
dissim3<- as.data.frame(dissim3)
dissim3 <- dissim3 %>% 
  rename(
    occ_2digit = Var1,
    white = Freq
)
dissim4 <- table(Nblackmen1990$occ_2digit)
dissim4 <- as.data.frame(dissim4)
dissim4 <- dissim4 %>% 
  rename(
    occ_2digit = Var1,
    black = Freq
    )

men1990dissim <- full_join(dissim3, dissim4, by = "occ_2digit")
men1990dissim$occ_2digit <- NULL
```

```{r}
# Setting up data to calculate index of dissimilarity, men 2000
dissim5 <- table(Nwhitemen2000$occ_2digit)
dissim5<- as.data.frame(dissim5)
dissim5 <- dissim5 %>% 
  rename(
    occ_2digit = Var1,
    white = Freq
)
dissim6 <- table(Nblackmen2000$occ_2digit)
dissim6 <- as.data.frame(dissim6)
dissim6 <- dissim6 %>% 
  rename(
    occ_2digit = Var1,
    black = Freq
    )

men2000dissim <- full_join(dissim5, dissim6, by = "occ_2digit")
men2000dissim$occ_2digit <- NULL
```

```{r}
# Setting up data to calculate index of dissimilarity, men 2010
dissim7 <- table(Nwhitemen2010$occ_2digit)
dissim7 <- as.data.frame(dissim7)
dissim7 <- dissim7 %>% 
  rename(
    occ_2digit = Var1,
    white = Freq
)
dissim8 <- table(Nblackmen2010$occ_2digit)
dissim8 <- as.data.frame(dissim8)
dissim8 <- dissim8 %>% 
  rename(
    occ_2digit = Var1,
    black = Freq
    )

men2010dissim <- full_join(dissim7, dissim8, by = "occ_2digit")
men2010dissim$occ_2digit <- NULL
```

```{r}
# Using seg to calculate index of dissimilarity, for men, each decade 
seg(men1980dissim)

seg(men1990dissim)

seg(men2000dissim)

seg(men2010dissim)
```

```{r}
# Setting up data to calculate index of dissimilarity, women 1980

dissim9 <- table(Nwhitewomen1980$occ_2digit)
dissim9 <- as.data.frame(dissim9)
dissim9 <- dissim9 %>% 
  rename(
    occ_2digit = Var1,
    white = Freq
)
dissim10 <- table(Nblackwomen1980$occ_2digit)
dissim10 <- as.data.frame(dissim10)
dissim10 <- dissim10 %>% 
  rename(
    occ_2digit = Var1,
    black = Freq
    )

women1980dissim <- full_join(dissim9, dissim10, by = "occ_2digit")
women1980dissim$occ_2digit <- NULL
```


```{r}
# Setting up data to calculate index of dissimilarity, women 1990
dissim11 <- table(Nwhitewomen1990$occ_2digit)
dissim11 <- as.data.frame(dissim11)
dissim11 <- dissim11 %>% 
  rename(
    occ_2digit = Var1,
    white = Freq
)
dissim12 <- table(Nblackwomen1990$occ_2digit)
dissim12 <- as.data.frame(dissim12)
dissim12 <- dissim12 %>% 
  rename(
    occ_2digit = Var1,
    black = Freq
    )

women1990dissim <- full_join(dissim11, dissim12, by = "occ_2digit")
women1990dissim$occ_2digit <- NULL

#Changing NAs to 0s so code runs correctly 
women1990dissim[is.na(women1990dissim)] <- 0
```

```{r}
# Setting up data to calculate index of dissimilarity, women 2000
dissim13 <- table(Nwhitewomen2000$occ_2digit)
dissim13 <- as.data.frame(dissim13)
dissim13 <- dissim13 %>% 
  rename(
    occ_2digit = Var1,
    white = Freq
)
dissim14 <- table(Nblackwomen2000$occ_2digit)
dissim14 <- as.data.frame(dissim14)
dissim14 <- dissim14 %>% 
  rename(
    occ_2digit = Var1,
    black = Freq
    )

women2000dissim <- full_join(dissim13, dissim14, by = "occ_2digit")
women2000dissim$occ_2digit <- NULL
```

```{r}
# Setting up data to calculate index of dissimilarity, women 2010
dissim15 <- table(Nwhitewomen2010$occ_2digit)
dissim15 <- as.data.frame(dissim15)
dissim15 <- dissim15 %>% 
  rename(
    occ_2digit = Var1,
    white = Freq
)
dissim16 <- table(Nblackwomen2010$occ_2digit)
dissim16 <- as.data.frame(dissim16)
dissim16 <- dissim16 %>% 
  rename(
    occ_2digit = Var1,
    black = Freq
    )

women2010dissim <- full_join(dissim15, dissim16, by = "occ_2digit")
women2010dissim$occ_2digit <- NULL

#Changing NAs to 0s so code runs correctly 
women2010dissim[is.na(women2010dissim)] <- 0
```

```{r}
# Using seg function to calculate index of dissimilarity for women, each decade
seg(women1980dissim)

seg(women1990dissim)

seg(women2000dissim)

seg(women2010dissim)
```