---
title: "IPUMS Demo"
author: "Jacob Hood"
date: "2/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ipumsr)
library(tidyverse)
library(kableExtra)
```

```{r}
ddi <- read_ipums_ddi("usa_00009.xml")
data <- read_ipums_micro(ddi)
summarise(data)
str(data$SEX)

head(data, n = 10) %>% kbl("html") %>% kable_classic_2(full_width = T)

```



```{r}
data_clean <- data %>%
  select(SAMPLE, SERIAL, PERNUM, PERWT, SEX, EDUC, INCWAGE)

# View first 10 rows
head(data_clean, n = 10) %>% kbl("html") %>% kable_classic_2(full_width = T)

```

```{r}
# Create a new variable called "unique_id"
data_clean <- data_clean %>%
  unite("unique_id",                # The name of the new column, as a string or symbol
        SAMPLE, SERIAL, PERNUM,     # Columns to unite
        sep = "",                   # Separator to use between values
        remove = TRUE)              # Remove input columns from output data frame

# Check data
head(data_clean, 10) %>% kbl("html") %>% kable_classic_2(full_width = T)

# Check how many unique values are there for the variable "unique_id"
n_distinct(data_clean$unique_id) 

# this should equal to: 
nrow(data_clean)

# Check number of observations for each value of EDUC (You can also use plotting)
table(data_clean$EDUC)

# Check coding scheme for EDUC in codebook
# --> we need to remove value 0, which means N/A or no schooling

# Check distribution of INCWAGE
data_clean %>%
  ggplot() +
  geom_histogram(aes(INCWAGE), binwidth = 15000, color = "black", fill = "grey")
  
# Check coding scheme for INCWAGE in codebook
# --> we need to remove value 999998 (missing) and value 999999 (N/A) 
max(data_clean$INCWAGE)

# Remove missing value use filter()
data_clean <- data_clean %>%
  filter(EDUC != 0 & INCWAGE < 999998)
# 4610 obs removed, 17322 obs left


# Check distribution after removing missing vaues
# EDUC
table(data_clean$EDUC)
```

```{r}
# INCWAGE
data_clean %>%
  ggplot() +
  geom_histogram(aes(INCWAGE), binwidth = 15000, color = "black", fill = "grey")
```


```{r}
data_clean %>%
  ggplot() +
  geom_point(aes(EDUC, INCWAGE)) +
  labs(title = "Scatterplot with EDUC on the x axis and INCWAGE on the y axis")
```

```{r}
ols_ipums <- lm(INCWAGE ~ EDUC, data = data_clean)
summary(ols_ipums)

data_clean %>%
  ggplot() +
  geom_point(aes(x = EDUC, y= INCWAGE)) +
  geom_smooth(aes(x = EDUC, y = INCWAGE, method = "lm")) +
  labs(title = "Scatterplot with EDUC on the x axis and INCWAGE on the y axis")
```



