---
title: "Lab 4 Demo"
author: "Jacob Hood"
date: "2/26/2021"
output:
  html_document: default
  pdf_document: default
---
install.packages('ipumsr')
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(kableExtra) 
library(ipumsr)
```

```{r}
# Value of x and y are observed
x <- c(-2, 0, 3, 6, 10) 
y <- c(-1, 8, 15, 12, 28)

# Create a dataframe of x and y
ols_df <- tibble(
  x = x,
  y = y
)
```


```{r}
# Check dataframe
ols_df %>% kbl("html") %>% kable_classic_2(full_width = F)

ols_df %>%
  ggplot() +
  geom_point(aes(x, y), shape = 1) +
  labs(title = "Scatterplot of Example Data")
```



```{r}
x_mean = mean(ols_df$x)
y_mean = mean(ols_df$y)
betaone <- sum((x -x_mean)*(y - y_mean))/sum((x - x_mean)^2)
betazero <- y_mean - betaone*x_mean

betaone
betazero
```

```{r}
rho = cor(ols_df$x, ols_df$y)
# Calculate sigma_x and sigma_y, which is the standard deviation of x and y
sigma_x = sd(ols_df$x)
sigma_y = sd(ols_df$y)

# This should equal to beta1 you got in Q1 and Q2
rho*sigma_y/sigma_x
```
```{r}
# Use mutate() to add the variable
ols_df_fit <- ols_df %>%
  mutate(fitted_y = betazero +betaone*x)

ols_df_fit
```


```{r}
ols_df_fit %>%
  mutate(squared_error = (y - fitted_y)^2) %>%
  summarise(sse = sum(squared_error))
```

```{r}
ols_df %>%
  ggplot() +
 geom_point(aes(x, y), shape = 1) +
  labs(title = "Scatterplot of Example Data with Fitted OLS Line") +
  geom_abline(intercept = betazero, slope = betaone) # plug in your beta results

ols_m1 <- lm(y ~ x, data = ols_df)

# check model result
ols_m1
summary(ols_m1)
```
```{r}
SSE <- ((ols_df$y) - (betazero + betaone*ols_df$x))^2 %>% sum()
SSE
```
```{r}
# Use the dataframe

# Create a variable equal to the squared error (y - fitted_y) of each row
ols_df_fit %>% 
  mutate(
    error = y - fitted_y, # you don't need to create this, this is for reference
    squared_error = (y - fitted_y)^2
    ) 
```
```{r}
ols_df %>%
  ggplot () +
  geom_point(aes(x,y), shape = 1) +
  labs(title = "Scatterplot of Example Data with Fitted OLS Line") +
  geom_abline(intercept = betazero, slope = betaone) # plug in your beta results
```

