---
title: "Problem Set 1"
author: "Jacob Hood"
date: "February 27th, 2021"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=70), tidy=TRUE, fig.pos = "H", echo = TRUE)
# Loading packages into environment 
library(formatR)
library(tidyverse)
library(gridExtra)
library(kableExtra)
```


```{r}
# Question 1

# 1.1: Formula for population mean

pop_mean <- function(x){
      out_vector <- sum(x)/length(x) # divide sum by total number of observations
      return(out_vector)
}
```

```{r}
# 1.2: Formula to calculate variance

pop_var <- function(x){
 var = sum((x - pop_mean(x))^2)/(length(x)) #(sum of each number - the mean)^2/sample size
 return(var)
}
```

```{r}
# 1.3 
 
gapminder <- read.csv("data/gapminder.csv")

pop_mean(gapminder$lifeExp)
pop_var(gapminder$lifeExp)

mean(gapminder$lifeExp)
var(gapminder$lifeExp)
# The mean value for both functions is 59.474. The variance for the function I wrote is 166.753. The variance for the R function is 166.852. They are different because my function calculcates population variance, while R's function calculates sample variance.
```

```{r} 
# Question #2

# Import data

parent_inc <- read.csv("data/parent_inc.csv")

# Tidy data

parent_inc %>%
  rename(father_income = fincome, mother_income = mincome) %>%
  pivot_longer(
  cols = c(father_name, mother_name, father_income, mother_income),
  names_to = c("type", ".value"),
  names_sep = "_"
  )
```    


```{r} 
# Question #3
# 3.1: Create a population data frame

value <- rnorm(n = 100000, mean = 5, sd = 1) %>% as_tibble()
```

```{r} 
# 3.2: Create a histogram 
value %>%
  ggplot(aes(value)) +
  geom_histogram(binwidth = 0.1, color = "black", fill = "grey") +
  geom_vline(aes(xintercept = mean(value)), color = "red", linetype = "dashed") +
  labs(title = "Histogram of Simulated Population with Normal Distribution", subtitle = "N = 100000, SD = 1")
```

```{r} 
# 3.3: Draw random sample n=50

set.seed(110001)
sample <- value %>% sample_n(size=50, replace = FALSE)
```

```{r} 
# 3.4: Plot a histogram of the sample

sample %>%
  ggplot(aes(value)) +
  geom_histogram(binwidth = .1, color = "black", fill = "grey") +  
  geom_vline(aes_string(xintercept = paste0('mean(', sample, ')')), color = "red", linetype = "dashed") +
  labs(title = "Histogram of Random Sample", subtitle = "N = 50")
```

```{r} 
# 3.5:

#Calculate point estimate for population mean
point_est <- sum(sample)/count(sample)
print(point_est)
```

```{r} 
# Calculate standard error of point estimate
standard_error <- sapply(sample, sd)/sqrt(length(sample))
print(standard_error)
```

```{r} 
# Calculate 95% confidence interval of point estimate

#The formula is: population mean +/- t-critical value * standard error

# Calculate critical value
observed_t <- point_est/standard_error
print(observed_t)

crit_val <- qt(p = .5*.05, df = 49)
print(crit_val)
```

```{r} 
# Caclulate confidence interval

upper_bound <- as.numeric(point_est) - (as.numeric(crit_val) * as.numeric(standard_error))
lower_bound <- as.numeric(point_est) + (as.numeric(crit_val) * as.numeric(standard_error))
CI <- c(lower_bound, upper_bound)
print(CI)
```

```{r} 
# 3.6 Simulate the sampling distribution of the sample mean (n = 50) using 1,000 draws

mean_container <- vector(mode = "numeric", length = 1000) 

set.seed(110001)
for (i in 1:1000){
  sample_two <- value %>% sample_n(size = 50, replace = FALSE)
  mean_container[i] <- mean(sample_two$value) 
}

head(mean_container, n = 10)
```

```{r} 
# 3.7 Create a histogram of the sampling distribution of the sample mean

mean_container %>%
  as_tibble %>%
  ggplot(aes(value)) +
  geom_histogram(binwidth = 0.01, color = "black", fill = "grey") +
  geom_vline(aes_string(xintercept = mean(mean_container)), color = "red", linetype = "dashed") +  
  labs(title = "Histogram of Sampling Distribution of Sample Mean Using 1,000 Draws", subtitle = "N = 50")
```

```{r} 
# 3.8 Calculate point estimate for population mean

point_est_two <- sum(mean_container)/length(mean_container)
print(point_est_two)
```

```{r} 

# Calculate standard error of point estimate

# Sample standard deviation/square root of sample size 

standard_error_two <- sd(mean_container)/sqrt(length(mean_container))
print(standard_error_two)
```

```{r} 

# Calculate 95% confidence interval of point estimate

# The formula is: population mean +/- t-critical value * standard error

# Calculate critical value

observed_t_two <- point_est_two/standard_error_two
print(observed_t_two)
 
crit_val_two <- qt(p = .5*.05, df = 49)
print(crit_val_two)

# Caclulate confidence interval

upper_bound_two <- as.numeric(point_est_two) - (as.numeric(crit_val_two) * as.numeric(standard_error_two))
lower_bound_two <- as.numeric(point_est_two) + (as.numeric(crit_val_two) * as.numeric(standard_error_two))
CI_two <- c(lower_bound_two, upper_bound_two)
print(CI_two)
```

```{r} 
# 3.9 Repeat questions 3 to 8 increasing sample size to n=1000

# a) Draw a random sample n=1,000

set.seed(110001)
final_sample <- value %>% sample_n(size=1000, replace = FALSE) %>% as_tibble() 
```

```{r} 
# b) Plot a histogram of the sample with appropriate title and labels

final_sample %>%
  ggplot(aes(value)) +
  geom_histogram(binwidth = 0.1, color = "black", fill = "grey") +
geom_vline(aes_string(xintercept = paste0('mean(', final_sample, ')')), color = "red", linetype = "dashed") +  labs(title = "Histogram of Random Sample", subtitle = "N = 1000")
```

```{r} 
# c) 
# Calculate point estimate

point_est_three <- sum(final_sample)/count(final_sample)
print(point_est_three)
```

```{r} 

# Calculate standard error of point estimate

standard_error_three <- sapply(final_sample, sd)/sqrt(length(final_sample)) 
print(standard_error_three)
```

```{r} 

# Calculate 95% confidence interval of point estimate
# The formula is: population mean +/- t-critical value * standard error

# Calculate critical value

observed_t_three <- point_est_three/standard_error_three
print(observed_t_three)

crit_val_three <- qt(p = .5*.05, df = 999)
print(crit_val_three)

# Caclulate confidence interval

upper_bound_three <- as.numeric(point_est_three) - (as.numeric(crit_val_three) * as.numeric(standard_error_three))
lower_bound_three <- as.numeric(point_est_three) + (as.numeric(crit_val_three) * as.numeric(standard_error_three))
CI_three <- c(lower_bound_three, upper_bound_three)
print(CI_three)
```

```{r} 
# d)

final_mean_container <- vector(mode = "numeric", length = 1000) 

set.seed(110001)
for (i in 1:1000){
  sample_three <- value %>% sample_n(size = 1000, replace = FALSE)
  final_mean_container[i] <- mean(sample_three$value) 
}

head(final_mean_container, n = 10)
```

```{r} 
# e) Create a histogram of the sampling distribution of the sample mean you simulated

final_mean_container %>%
  as_tibble %>%
  ggplot(aes(value)) +
  geom_histogram(binwidth = 0.01, color = "black", fill = "grey") +
geom_vline(aes_string(xintercept = mean(final_mean_container)), color = "red", linetype = "dashed") +  labs(title = "Histogram of Sampling Distribution of Sample Mean Using 1,000 Draws", subtitle = "N = 1000")
```

```{r} 
# f.1) Calculate point estimate for population mean

point_est_four <- sum(final_mean_container)/length(final_mean_container)
print(point_est_four)
```

```{r} 

# f.2) Calculate standard error of point estimate

#Sample standard deviation/square root of sample size

standard_error_four <- sd(final_mean_container)/sqrt(length(final_mean_container))
print(standard_error_four)
```

```{r} 
# f.3) Calculate 95% confidence interval of point estimate

#The formula is: population mean +/- t-critical value * standard error

# Calculate critical value

observed_t_four <- point_est_four/standard_error_four
print(observed_t_four)

crit_val_four <- qt(p = .5*.05, df = 999)
print(crit_val_four)

# Caclulate confidence interval

upper_bound_four <- as.numeric(point_est_four) - (as.numeric(crit_val_four) * as.numeric(standard_error_four))
lower_bound_four <- as.numeric(point_est_four) + (as.numeric(crit_val_four) * as.numeric(standard_error_four))
CI_four <- c(lower_bound_four, upper_bound_four)
print(CI_four)

# The concept being demonstrated here is the (Weak) Law of Large Numbers. As the sample size increases, and the number of samples draws increases, the sample mean more nearly equals the population mean. This is evidenced by the smaller standard errors and smaller confidence intervals, showing that the estimator became more precise.
```

