---
title: "Hood Replication Project"
author: "Jacob Hood"
date: "4/1/2021"
output: pdf_document
---

## Setting up environment 
```{r setup, include=FALSE, results = "asis"}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
p_load(tidyverse, ipumsr, kableExtra, data.table, seg, stargazer, tables, xtable)
```

## Loading data into environment
```{r loading data}
ddi <- read_ipums_ddi("usa_00004.xml")
data <- read_ipums_micro(ddi)
crosswalk_data <- read.csv("occ_crosswalk.csv")
```

## Cleaning data
```{r selecting variables}
# Selecting variables to keep 
data_clean <- data %>%
  select(YEAR, SAMPLE, SERIAL, PERNUM, PERWT, REGION,	METRO,	NCHILD,	NCHLT5,	SEX, AGE,	MARST, RACE, HISPAN, BPL, EDUC, EDUCD, LABFORCE,	CLASSWKR, CLASSWKRD, OCC1990,	WKSWORK1, WKSWORK2,	UHRSWORK, INCWAGE)
```

```{r remove percentiles}
# Removing the top (99%) and bottom (1%) income percentiles 
data_clean <- data_clean %>% group_by(YEAR) %>% filter(INCWAGE != 0) %>% filter(INCWAGE < quantile(data_clean$INCWAGE, 0.99) & INCWAGE > quantile(data_clean$INCWAGE, 0.01))
```

```{r select correct obvs}
# Filtering out people active in labor force, black or white, ages 25-59, and not Hispanic
data_clean <- data_clean %>% 
  filter(LABFORCE == 2 & AGE <= 59 & AGE >= 25 & HISPAN == 0 & RACE < 3) %>%
  filter(EDUC != 0 & INCWAGE < 999998 & UHRSWORK != 00) %>%
  filter(WKSWORK1 !=0 | WKSWORK2 != 0)  # Removing missing values for education and income
```

```{r}
# For grouped school years, setting years of schooling to the mean
data_clean <- data_clean %>% mutate(EDUY = ifelse(EDUC == 01, 4, ifelse(EDUC == 02, 9, ifelse(EDUC == 03, 11, ifelse(EDUC == 04, 12, ifelse(EDUC == 05, 13, ifelse(EDUC == 06, 14, ifelse(EDUC == 07, 15, ifelse (EDUC == 08, 16, ifelse (EDUC == 08, 17, ifelse(EDUC == 09, 17, ifelse(EDUC == 10, 18, 21))))))))))))
```

```{r}
# Joining with crosswalk data
# I have to convert the data and merge it otherwise my computer's memory gets exhausted
# So apologies for the ugly code!

names(crosswalk_data)[names(crosswalk_data) == "occ1990"] <- "OCC1990"
# Extract the data in a data.table format 
    # can be replaced by reading from a file using fread or any other command to have both data sets as data tables.
dt1 <- as.data.table(data_clean) 
dt2 <- as.data.table(crosswalk_data)

# set the merging key in each data table
setkey(dt1, "OCC1990")
setkey(dt2, "OCC1990")
# merge data tables
dt.result <- merge(dt1, dt2, by = "OCC1990")

data_clean <- as.data.frame(dt.result)
```

```{r new variables}
# Finally, create new variables for log weekly hours worked, weekly wage, log weekly wage (all adjusted for inflation), potential work experience,
# and potential work experience squared 

# recoding WKSWORK2 to values centered on the mean for Year 2010
data_clean <- data_clean %>% mutate(ADJWKSWORK2 = ifelse(WKSWORK2 == 1, 7, ifelse(WKSWORK2 == 2, 20, ifelse (WKSWORK2 == 3, 33, ifelse(WKSWORK2 == 4, 43.5, ifelse(WKSWORK2 == 5, 48.5, 51))))))

 # adjusting for inflation (1999 dollars)
data_clean <- data_clean %>% mutate(ADJINCWAGE = ifelse(YEAR == 1980, INCWAGE*2.295, ifelse(YEAR == 1990, INCWAGE*1.334, ifelse(YEAR == 2000, INCWAGE, INCWAGE*0.764)))) %>% 
  mutate("LOGWKSWRK" = ifelse(YEAR == 2010, log(ADJWKSWORK2), log(WKSWORK1)), "WKWAGE" = ifelse(YEAR == 2010, ADJINCWAGE/ADJWKSWORK2, ADJINCWAGE/WKSWORK1), "LOGWKWAGE" = ifelse(YEAR == 2010, log(ADJINCWAGE/ADJWKSWORK2), log(ADJINCWAGE/WKSWORK1)), "PWRKEXP" = (AGE - EDUY - 6), "SQ_PWRKEXP" = PWRKEXP^2)
```

```{r new variables}
# Renaming the dummy sex and race variables to character strings, and creating a new variable for both race and gender
data_clean <- data_clean %>% mutate(GENDER = ifelse(SEX == 1, "male", "female")) %>% mutate(RACE = ifelse(RACE == 1, "white", "black" )) %>% mutate(RACEGENDER = ifelse(GENDER == "male" & RACE == "white", "white male", ifelse(GENDER == "female" & RACE== "white", "white female", ifelse(GENDER == "male" & RACE == "black", "black male", "black female"))))
```

```{r}
# Creating variable for Foreign Born (=1)
data_clean <- data_clean %>% mutate(ForeignBorn = ifelse(BPL >= 150, 1, 0)) %>%
# Creating variable for Public Sector (=1)
mutate(PublicSector = ifelse(CLASSWKRD >= 24 & CLASSWKRD < 29, 1, 0))
```

```{r}
# Creating variable for College (=1)
data_clean <- data_clean %>% mutate(College = ifelse(EDUC >= 10 , 1, 0 )) %>%

# Creating variable for Some College (=1)
mutate(SomeCol = ifelse(EDUC > 06 & EDUC < 10, 1, 0)) %>%

# Creating variable for High School (=1)
mutate(HSGrad = ifelse(EDUC ==06, 1, 0)) %>%

  # Creating variable for Less than high school (=1)
mutate(LessHS = ifelse(EDUC < 06, 1, 0))
```

```{r}
# Creating variable for Married (=1)
data_clean <- data_clean %>% mutate(Married = ifelse(MARST == 1 | MARST ==2, 1, 0)) %>%

# Creating variable for Presence of Child Under 5 (=1)
mutate(Child5 = ifelse(NCHLT5 == 0, 0, 1))
```

```{r}
# Creating variable for Northeast Region (=1)
data_clean <- data_clean %>% mutate(Northeast = ifelse(REGION == 11 | REGION == 12, 1, 0)) %>%

# Creating variable for Midwest Region (=1)
mutate(Midwest = ifelse(REGION == 21 | REGION == 22, 1, 0)) %>%

# Creating variable for South Region (=1)
mutate(South = ifelse(REGION == 31 | REGION == 32 | REGION == 33, 1, 0)) %>%
  
# Creating variable for West Region (=1)
mutate(West = ifelse(REGION == 42 | REGION == 43, 1, 0)) %>%

# Creating variable for Metro (=1)
 mutate(Metro = ifelse(METRO >= 2, 1, 0))

```

## Descriptive Statistics 
```{r TableA1a}
# Creating TableA1a
TableA1A <- data_clean %>% filter(GENDER == "male") %>% group_by(YEAR, RACE) %>%
  summarise("Weekly wage" = mean(WKWAGE),
            "Weekly wage (logged)" = mean(LOGWKWAGE),
            "Weekly working hours" = mean(UHRSWORK),
            "Weekly working hours (logged)" = mean(log(UHRSWORK)),
            "Public sector (=1)" = mean(PublicSector),
            "College (=1)" = mean(College),
            "Some college (=1)" =  mean(SomeCol),
            "High school graduate (=1)" =  mean(HSGrad),
            "Less than high school (=1)" =  mean(LessHS),
            "Potential work experience" =  mean(PWRKEXP),
            "Potential wok experience sq." =  mean(SQ_PWRKEXP),
            "Married (=1)" =  mean(Married),
            "Number of children" =  mean(NCHILD),
            "Child under 5 (=1)" =  mean(Child5),
            "Foreign born (=1)" =  mean(ForeignBorn),
            "Northeast region (=1)" =  mean(Northeast),
            "Midwest region (=1)" =  mean(Midwest),
            "South region (=1)" =  mean(South),
            "West region (=1)" =  mean(West),
            "Lives in metropolitan area (=1)" = mean(Metro))
TableA1A
```

```{r TableA1b}
# Creating TableA1b
TableA1B <- data_clean %>% filter(GENDER == "female") %>% group_by(YEAR, RACE) %>%
  summarise("Weekly wage" = mean(WKWAGE),
            "Weekly wage (logged)" = mean(LOGWKWAGE),
            "Weekly working hours" = mean(UHRSWORK),
            "Weekly working hours (logged)" = mean(log(UHRSWORK)),
            "Public sector (=1)" = mean(PublicSector),
            "College (=1)" = mean(College),
            "Some college (=1)" =  mean(SomeCol),
            "High school graduate (=1)" =  mean(HSGrad),
            "Less than high school (=1)" =  mean(LessHS),
            "Potential work experience" =  mean(PWRKEXP),
            "Potential wok experience sq." =  mean(SQ_PWRKEXP),
            "Married (=1)" =  mean(Married),
            "Number of children" =  mean(NCHILD),
            "Child under 5 (=1)" =  mean(Child5),
            "Foreign born (=1)" =  mean(ForeignBorn),
            "Northeast region (=1)" =  mean(Northeast),
            "Midwest region (=1)" =  mean(Midwest),
            "South region (=1)" =  mean(South),
            "West region (=1)" =  mean(West),
            "Lives in metropolitan area (=1)" = mean(Metro))
            
TableA1B
```

```{r}
# Transposing table and exporting to latex
TableA1A <- t(TableA1A)
xtable(TableA1A)
```

```{r}
# Transposing table and exporting to latex
TableA1B <- t(TableA1B)
xtable(TableA1B)
```

```{r}
# Calculating N  men
Nwhitemen1980 <- data_clean %>% filter(RACEGENDER == "white male") %>% filter(YEAR == "1980")
nrow(Nwhitemen1980)
Nblackmen1980 <- data_clean %>% filter(RACEGENDER == "black male") %>% filter(YEAR == "1980")
nrow(Nblackmen1980)
Nwhitemen1990 <- data_clean %>% filter(RACEGENDER == "white male") %>% filter(YEAR == "1990")
nrow(Nwhitemen1990)
Nblackmen1990 <- data_clean %>% filter(RACEGENDER == "black male") %>% filter(YEAR == "1990")
nrow(Nblackmen1990)
Nwhitemen2000 <- data_clean %>% filter(RACEGENDER == "white male") %>% filter(YEAR == "2000")
nrow(Nwhitemen2000)
Nblackmen2000 <- data_clean %>% filter(RACEGENDER == "black male") %>% filter(YEAR == "2000")
nrow(Nblackmen2000)
Nwhitemen2010 <- data_clean %>% filter(RACEGENDER == "white male") %>% filter(YEAR == "2010")
nrow(Nwhitemen2010)
Nblackmen2010 <- data_clean %>% filter(RACEGENDER == "black male") %>% filter(YEAR == "2010")
nrow(Nblackmen2010)
```

```{r}
# Calculating N  women
Nwhitewomen1980 <- data_clean %>% filter(RACEGENDER == "white female") %>% filter(YEAR == "1980")
nrow(Nwhitewomen1980)
Nblackwomen1980 <- data_clean %>% filter(RACEGENDER == "black female") %>% filter(YEAR == "1980")
nrow(Nblackwomen1980)
Nwhitewomen1990 <- data_clean %>% filter(RACEGENDER == "white female") %>% filter(YEAR == "1990")
nrow(Nwhitewomen1990)
Nblackwomen1990 <- data_clean %>% filter(RACEGENDER == "black female") %>% filter(YEAR == "1990")
nrow(Nblackwomen1990)
Nwhitewomen2000 <- data_clean %>% filter(RACEGENDER == "white female") %>% filter(YEAR == "2000")
nrow(Nwhitewomen2000)
Nblackwomen2000 <- data_clean %>% filter(RACEGENDER == "black female") %>% filter(YEAR == "2000")
nrow(Nblackwomen2000)
Nwhitewomen2010 <- data_clean %>% filter(RACEGENDER == "white female") %>% filter(YEAR == "2010")
nrow(Nwhitewomen2010)
Nblackwomen2010 <- data_clean %>% filter(RACEGENDER == "black female") %>% filter(YEAR == "2010")
nrow(Nblackwomen2010)
```

```{r}
# Plotting Figure 1
fig1data <- data_clean %>% group_by(YEAR, RACEGENDER) %>% summarise(AVGWKWAGE = mean(WKWAGE)) # grouping data by year/group and averaging weekly wage

fig1 <- fig1data %>%
  ggplot(aes(YEAR, y = AVGWKWAGE, linetype = RACEGENDER)) +
  geom_line() + 
  geom_point(aes(shape = RACEGENDER), size = 3) +
  labs(x = "", y = "" , title = "Figure 1. Average Weekly Earnings (in Constant $US) by Race and Gender, 1980 to 2010") +
    scale_linetype_manual(values = c("dashed", "dashed" , "solid", "solid"), label = c("Black Female", "Black Male", "White Female", "White Male")) +
  scale_shape_manual(values = c(24, 22 , 17, 15), label = c("Black Female", "Black Male", "White Female", "White Male")) + 
  theme(legend.title = element_blank()) +
  ylim(300, 1100) 
```

## Regression Analysis
```{r}
# Running linear models for men, by race and year
m1980whitemen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + UHRSWORK + Metro + PublicSector + Midwest + South + West, data = Nwhitemen1980)
m1980blackmen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + UHRSWORK + Metro + PublicSector + Midwest + South + West, data = Nblackmen1980)
m1990whitemen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + UHRSWORK + Metro + PublicSector + Midwest + South + West, data = Nwhitemen1990)
m1990blackmen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + UHRSWORK + Metro + PublicSector + Midwest + South + West, data = Nblackmen1990)
m2000whitemen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + UHRSWORK + Metro + PublicSector + Midwest + South + West, data = Nwhitemen2000)
m2000blackmen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + UHRSWORK + Metro + PublicSector + Midwest + South + West, data = Nblackmen2000)
m2010whitemen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + UHRSWORK + Metro + PublicSector + Midwest + South + West, data = Nwhitemen2010)
m2010blackmen <-lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + UHRSWORK + Metro + PublicSector + Midwest + South + West, data = Nblackmen2010)

```

```{r}
# Model table for men
stargazer(m1980whitemen, m1980blackmen, m1990whitemen, m1990blackmen, m2000whitemen, m2000blackmen, m2010whitemen, m2010blackmen, type = "text")
```

```{r}
# Running linear models for women, by race and year
m1980whitewomen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + UHRSWORK + Metro + PublicSector + Midwest + South + West, data = Nwhitewomen1980)
m1980blackwomen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + UHRSWORK + Metro + PublicSector + Midwest + South + West, data = Nblackwomen1980)
m1990whitewomen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + UHRSWORK + Metro + PublicSector + Midwest + South + West, data = Nwhitewomen1990)
m1990blackwomen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + UHRSWORK + Metro + PublicSector + Midwest + South + West, data = Nblackwomen1990)
```


```{r}
m2000whitewomen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + UHRSWORK + Metro + PublicSector + Midwest + South + West, data = Nwhitewomen2000)
m2000blackwomen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + UHRSWORK + Metro + PublicSector + Midwest + South + West, data = Nblackwomen2000)
m2010whitewomen <- lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + UHRSWORK + Metro + PublicSector + Midwest + South + West, data = Nwhitewomen2010)
m2010blackwomen <-lm(LOGWKWAGE ~  PWRKEXP + SQ_PWRKEXP + LessHS +  HSGrad + SomeCol + NCHILD + Child5 + Married + ForeignBorn + UHRSWORK + Metro + PublicSector + Midwest + South + West, data = Nblackwomen2010)
```

